#!/bin/sh
#
# A hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#

# Catch duplicate Signed-off-by lines.

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}

commit_message="$1"
# exit with a non zero exit code incase of an invalid commit message


# use git-conventional-commits, see https://github.com/leibniz-psychology/datawiz2/wiki/Contributing#-commit-message-guideline
yarn commitlint --edit "$commit_message"