#!/bin/sh
#
# An hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.


echo "Run pre-commit hook..."

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi


# Perform Lint Tests
set -e

echo ""
echo "Lint Markdown..."
yarn markdownlint-cli2 '**/*.md' '#node_modules' '#vendor' '#tools'

echo ""
echo "Lint PHP Files..."

PHP_CS_FIXER="tools/php-cs-fixer/vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false

if [ -x $PHP_CS_FIXER ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    FILES=` git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | tr '\n' ' '`
    if [ -z "$FILES" ]
	then
		  echo "No php files found in commit."
	else
		  echo ${FILES}
		  $PHP_CS_FIXER fix --config .php-cs-fixer.php --verbose ${FILES} --diff
		  git add ${FILES}
	fi
else
    echo ""
    echo "Please install php-cs-fixer with"
    echo ""
    echo "   composer install"
    echo "or"
    echo "   mkdir -p tools/php-cs-fixer"
    echo "   composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer"
    echo ""
    exit 1
fi

echo ""
echo "Lint non-PHP Files..."
php ./bin/console lint:container
php ./bin/console lint:twig
php ./bin/console lint:yaml .github/workflows config/ translations/
php ./bin/console lint:container
composer validate --strict
echo ""


