# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.project_dir%/var/uploads'
    filesystems:
        assets:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
