# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        materials: # this endpoint is only for additional materials
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: oneup_flysystem.assets_filesystem # see oneup_flysystem.yaml
        datasets: # this endpoint will handle the datasets (spss, csv, tsv)
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: oneup_flysystem.assets_filesystem #see oneup_flysystem.yaml
            allowed_mimetypes:
                text/csv: ['csv']
                text/tab-separated-values: ['tsv', 'tab']
                text/plain: ['csv', 'tsv', 'tab', 'txt']
                application/octet-stream: ['sav']