doctrine:
    dbal:
        default_connection: dev
        connections:
            sqlite:
                # sqlite, but overwritten by DATA_URL
                url: '%env(resolve:DATABASE_URL)%'
                override_url: true
            mysql:
                # mysql, but overwritten by DATA_URL
                url: '%env(resolve:DATABASE_URL)%'
                override_url: true
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/source/Domain/Model'
                prefix: 'App\Domain\Model'
                alias: App
        filters:
            ownership: App\Security\Authorization\OwnershipFilter
