security:
    # IMPORTANT: The processing in Symfony changed. This file is evaluated AFTER your env config
    # It will therefore override your configuration and completly mess up your authentication
    # Please, prevent any firewall config here

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^pages/administration/profile, roles: ROLE_USER }
        - { path: ^pages/administration/dashboard, roles: ROLE_USER }
        - { path: ^pages/*, roles: ROLE_USER }

