File-deletion:
  path: /filemanagement/delete/{uuid}/material
  controller: App\View\Controller\FileManagementController::deleteMaterialCall

Codebook-dataupdate:
  path: /codebook/{uuid}/data
  controller: App\View\Controller\CodebookController::dataUpdateCall

Codebook-measures:
  path: /codebook/{uuid}/measures
  controller: App\View\Controller\CodebookController::measuresCall