Study-root:
  path: /studies
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: Study-overview
    permanent: true

Study-index:
  path: /studies/index
  controller: App\View\Controller\StudyController::indexAction

Study-overview:
  path: /studies/overview
  controller: App\View\Controller\StudyController::overviewAction

Study-new:
  path: /studies/new
  controller: App\View\Controller\StudyController::newAction

Study-settings:
  path: /studies/{uuid}/settings
  controller: App\View\Controller\StudyController::settingsAction

Study-documentation:
  path: /studies/documentation
  controller: App\View\Controller\StudyController::documentationAction

Study-admin:
  path: /studies/admin
  controller: App\View\Controller\StudyController::adminAction

Study-theory:
  path: /studies/theory
  controller: App\View\Controller\StudyController::theoryAction

Study-design:
  path: /studies/design
  controller: App\View\Controller\StudyController::designAction

Study-sample:
  path: /studies/sample
  controller: App\View\Controller\StudyController::sampleAction