Study-root:
  path: /studies
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: Study-overview
    permanent: true

Study-overview:
  path: /studies/overview
  controller: App\View\Controller\StudyController::overviewAction

Study-new:
  path: /studies/new
  controller: App\View\Controller\StudyController::newAction

Study-settings:
  path: /studies/{uuid}/settings
  controller: App\View\Controller\StudyController::settingsAction

Study-documentation:
  path: /studies/{uuid}/documentation
  controller: App\View\Controller\StudyController::documentationAction

Study-theory:
  path: /studies/{uuid}/theory
  controller: App\View\Controller\StudyController::theoryAction

Study-design:
  path: /studies/{uuid}/design
  controller: App\View\Controller\StudyController::designAction

Study-sample:
  path: /studies/{uuid}/sample
  controller: App\View\Controller\StudyController::sampleAction

Study-measure:
  path: /studies/{uuid}/measure
  controller: App\View\Controller\StudyController::measureAction

Study-method:
  path: /studies/{uuid}/method
  controller: App\View\Controller\StudyController::methodAction

Administration-profile:
  path: /administration/profile
  controller: App\View\Controller\AdministrationController::profileAction