---
apiVersion: v1
kind: Service
metadata:
  name: datawiz2
  labels:
    app: datawiz2
spec:
  ports:
    - port: 80
  selector:
    app: datawiz2
---
apiVersion: v1
kind: Service
metadata:
  name: datawiz2-mysql
  labels:
    app: datawiz2
spec:
  ports:
    - port: 3306
  selector:
    app: datawiz2
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datawiz2-mysql
  labels:
    app: datawiz2
spec:
  selector:
    matchLabels:
      app: datawiz2
      tier: mysql
  replicas: 1 # tells deployment to run 1 pods matching the template
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datawiz2
        tier: mysql
    spec:
      volumes:
        - name: datawiz2-persistent-dbs
          persistentVolumeClaim:
            claimName: datawiz2-pv-dbs-claim
      containers:
        - image: crzpiddev.azurecr.io/mariadb:10.7.1
          name: mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: 100m
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: devzpid
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: datawiz2-persistent-dbs
              mountPath: /var/lib/mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datawiz2
spec:
  selector:
    matchLabels:
      app: datawiz2
  replicas: 1 # tells deployment to run 2 pods matching the template
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: datawiz2
        tier: frontend
    spec:
      volumes:
        - name: shared-files
          emptyDir: { }
        - name: datawiz2-persistent-storage
          persistentVolumeClaim:
            claimName: datawiz2-pv-files-claim
      containers:
        - name: php
          image: crzpiddev.azurecr.io/datawiz2_php_fpm:latest-dev
          resources:
            requests:
              memory: "128Mi"
              cpu: 100m
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: DATABASE_URL
              value: mysql://root:devzpid@datawiz2-mysql:3306/app?serverVersion=mariadb-10.7.1&charset=utf8
            - name: SPSS_API_URI
              value: 127.0.0.1:8081/api
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /var/www
            - name: datawiz2-persistent-storage
              mountPath: /var/www/var/uploads
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r -p /build/. /var/www" ]
        - name: nginx
          image: crzpiddev.azurecr.io/datawiz2_nginx:latest-dev
          resources:
            requests:
              memory: "128Mi"
              cpu: 100m
            limits:
              memory: "512Mi"
              cpu: "1"
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /var/www
          ports:
            - containerPort: 80
        - name: spss
          image: crzpiddev.azurecr.io/datawiz2_spss:latest-dev
          resources:
            requests:
              memory: "128Mi"
              cpu: 100m
            limits:
              memory: "512Mi"
              cpu: "1"
          imagePullPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datawiz2
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    external-dns.alpha.kubernetes.io/hostname: datawiz2.dev.zpid.org
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-599"
    appgw.ingress.kubernetes.io/health-probe-interval: "10"
    appgw.ingress.kubernetes.io/health-probe-timeout: "15"
    appgw.ingress.kubernetes.io/request-timeout: "100"
spec:
  tls:
    - secretName: cert-devwildcard
  rules:
    - host: datawiz2.dev.zpid.org
      http:
        paths:
          - path:
            backend:
              serviceName: datawiz2
              servicePort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: datawiz2.mysql
  namespace: development
spec:
  podSelector:
    matchLabels:
      app: datawiz2
      tier: mysql
  ingress:
    - ports:
        - port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: datawiz2.frontend
  namespace: development
spec:
  podSelector:
    matchLabels:
      app: datawiz2
      tier: frontend
  ingress:
    - ports:
        - port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datawiz2-pv-files-claim
  labels:
    app: datawiz2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datawiz2-pv-dbs-claim
  labels:
    app: datawiz2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
