index:
    path: /index
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      route: Administration-landing

root:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: Administration-landing
    permanent: true

Study-root:
  path: /studies
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: Study-overview
    permanent: true

# This shouldn't be necessary, but it solves a bug
index-bug:
  path: /pages/administration/landing
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: Administration-landing
    permanent: true