index:
    path: /index
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      route: Administration-landing

root:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: index
    permanent: true

Study-root:
  path: /studies
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: Study-overview
    permanent: true
