name: Container Build

on:
  workflow_call:
    inputs:
      container-tag:
        type: string
        description: 'Container tag'
        required: true
      build-stage:
        type: string
        description: 'Type: dev/prod'
        required: true
        default: dev

jobs:
  build:
    name: Build App Container (${{ inputs.build-stage }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      APP: datawiz2
      GH_SHA: ${{ github.sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Connect to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Create SPSS-API image build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_spss:${{ env.GH_SHA }}  --file .github/workflows/manifests/spss_api/Dockerfile
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_spss:${{ env.GH_SHA }}

      - name: set SPSS-API container tag
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_spss:${{ env.GH_SHA }}
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_spss:${{ env.GH_SHA }} ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_spss:${{ inputs.container-tag }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_spss:${{ inputs.container-tag }}

      - name: Create PHP-FPM image build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_php_fpm:${{ env.GH_SHA }}  --file .github/workflows/manifests/php/${{ inputs.build-stage }}.Dockerfile
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_php_fpm:${{ env.GH_SHA }}

      - name: set PHP-FPM container tag
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_php_fpm:${{ env.GH_SHA }}
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_php_fpm:${{ env.GH_SHA }} ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_php_fpm:${{ inputs.container-tag }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_php_fpm:${{ inputs.container-tag }}

      - name: Create NGINX image and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_nginx:${{ env.GH_SHA }}  --file .github/workflows/manifests/nginx/Dockerfile
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_nginx:${{ env.GH_SHA }}

      - name: set NGINX container tag
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_nginx:${{ env.GH_SHA }}
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_nginx:${{ env.GH_SHA }} ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_nginx:${{ inputs.container-tag }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP }}_nginx:${{ inputs.container-tag }}