name: DataWiz 2 Build
on:
  workflow_dispatch:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  DATABASE_URL: mysql://root:root@127.0.0.1:3306/dashboard?serverVersion=8.0
  TRUSTED_PROXIES: ${{ secrets.TRUSTED_PROXIES }}
  APP_ENV: dev
  APP_SECRET: ${{ secrets.APP_SECRET }}
  OAUTH_KEYCLOAK_CLIENT_ID: ${{ secrets.OAUTH_KEYCLOAK_CLIENT_ID }}
  OAUTH_KEYCLOAK_CLIENT_SECRET: ${{ secrets.OAUTH_KEYCLOAK_CLIENT_SECRET }}
  OAUTH_KEYCLOAK_AUTH_SERVER_URL: ${{ secrets.OAUTH_KEYCLOAK_AUTH_SERVER_URL }}
  OAUTH_KEYCLOAK_REALM: ${{ secrets.OAUTH_KEYCLOAK_REALM }}
  CYPRESS_BASE_URL: https://localhost:8000
  CYPRESS_kcRedirectUri: https://localhost:8000
  CYPRESS_kcRoot: ${{ secrets.CYPRESS_KEYCLOAK_URL }}
  CYPRESS_kcRealm: ${{ secrets.OAUTH_KEYCLOAK_REALM }}
  CYPRESS_kcClient: ${{ secrets.OAUTH_KEYCLOAK_CLIENT_ID }}
  CYPRESS_username: ${{ secrets.CYPRESS_username }}
  CYPRESS_password: ${{ secrets.CYPRESS_password }}
  CYPRESS_loginPath: /security/login
  CYPRESS_logoutPath: /security/logout
  extensions: zip intl gd mysqli

jobs:
  symfony:
    name: Symfony 5.4 (PHP ${{ matrix.php-versions }})
    runs-on: self-hosted
    services:
      database:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:
      - name: Install Symfony CLI
        run: wget https://get.symfony.com/cli/installer -O - | bash

      - name: Install missing libs
        run: sudo apt-get update -y && sudo apt install -y libsodium-dev yarn

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: ${{ env.extensions }}
          version: 2

      - name: Install Yarn dependencies
        run: yarn install

      - name: Encore generate dev build
        run: yarn encore dev

      - name: Make Migrations
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Start Server
        run: |
          /home/runner/.symfony/bin/symfony server:ca:install
          /home/runner/.symfony/bin/symfony serve -d

      - name: Run Cypress
        run: npx cypress run -b chrome --headless


