name: Dev Workflow

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

jobs:
  call-lint-workflow:
    uses: ./.github/workflows/lint.yml

  #call-e2e-workflow:
  #  needs:
  #    - call-lint-workflow
  #  uses: ./.github/workflows/e2e.yml
  #  secrets: inherit

  call-container-build-workflow:
    needs:
      - call-lint-workflow
    uses: ./.github/workflows/container-build.yml
    with:
      container-tag: latest-dev
      build-stage: dev
    secrets: inherit