name: Main Workflow

on:
  push:
    branches: [ master ]

jobs:
  call-e2e-workflow:
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  call-container-build-workflow:
    needs:
      - call-e2e-workflow
    uses: ./.github/workflows/container-build.yml
    with:
      container-tag: latest
      build-stage: prod
    secrets: inherit