name: Main Workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main]
jobs:
    call-lint-workflow:
        uses: ./.github/workflows/lint.yml

    call-test-workflow:
        uses: ./.github/workflows/test.yml

    call-container-build-workflow:
        needs:
            - call-lint-workflow
            - call-test-workflow
        uses: ./.github/workflows/container-build.yml
        with:
            container-tag: latest
            build-stage: prod
        secrets: inherit
